server:
  port: 8081

spring:
  #配置数据源
  datasource:
    #配置连接数据库的信息
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: kuzan
    password: kuzan6666
    type: com.zaxxer.hikari.HikariDataSource

#MyBatis-Plus相关配置
mybatis-plus:
  configuration:
    #日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
